runtime: java11
instance_class: B4
manual_scaling:
  instances: 1


env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=512m -XX:ActiveProcessorCount=2 -Xmx512m -agentpath:/opt/cprof/profiler_java_agent.so=-logtostderr,-cprof_enable_heap_sampling=true"


liveness_check:
  path: "/liveness_check"
  check_interval_sec: 60
  timeout_sec: 600
  failure_threshold: 10
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 60
  timeout_sec: 600
  failure_threshold: 10
  success_threshold: 2
  app_start_timeout_sec: 300